### ISSUE TITLE
Would BigFloat see benefits similar to the BigInt speedup?

### ISSUE THREAD

**Issue by JeffreySarnoff** [JuliaOpt/MutableArithmetics.jl#24]

**Comment by Peiffap** [comment]
Yes; over the summer, I wrote some code that works on `BigFloat`, which I needed to run some benchmarks for a Gröbner basis computation; the precise syntax might have changed a bit since then (@blegat would know more about that), but [here's the link](https://peiffap.wordpress.com/2019/08/26/gsoc-19-a-summary/); the part you're interested in is down in the section on Gröbner basis computations.

I do recall though that Base seems to have less functionalities built-in for `BigFloat` than it does for `BigInt`.

**Comment by JeffreySarnoff** [comment]
My interest is in accelerating some heavily used functionality within [`ArbNumerics.jl`](https://github.com/JeffreySarnoff/ArbNumerics.jl).  The types provided are each Julia-realized interfaces to an underlying C library which provides its own, rather large collection of functioning mathematical parts.  What are the lower level procedures and basic operations which are most helpful in accelerating performance with your approach?

**Comment by blegat** [comment]
I would imagine that for instance `ArbFloat` could implement MutableArithmetics similarly to how it's implemented for `BigInt`.
That would allow to reuse `ArbFloat` instead of allocating new ones.
It seems that similarly to `BigInt`, you need to create a new `ArbFloat` to contain the result of an addition:
```julia
julia> function f()
       a = ArbFloat(1)
       b = ArbFloat(2)
       c = @time a + b
       end
f (generic function with 2 methods)

julia> f()
  0.000002 seconds (1 allocation: 48 bytes)
3.0

julia> f()
  0.000004 seconds (1 allocation: 48 bytes)
3.0

julia> f()
  0.000004 seconds (1 allocation: 48 bytes)
3.0
```
The issue is that when you call `sum`, you create one each time you call `+`, so the memory allocated grows linearly with the length of the vector being summed:
```julia
julia> function g()
       a = ArbFloat.(1:1000)
       @time sum(a)
       end
g (generic function with 1 method)

julia> g()
  0.024945 seconds (66.36 k allocations: 3.483 MiB)
500500.0

julia> g();
  0.000134 seconds (999 allocations: 46.828 KiB)

julia> g();
  0.000113 seconds (999 allocations: 46.828 KiB)

julia> g();
  0.000162 seconds (999 allocations: 46.828 KiB)
```
If `ArbFloat` implements `MA.mutable_operate_to!(::ArbFloat, ::typeof(+), ::ArbFloat, ::ArbFloat)`, you can do
```julia
function better_sum(x::Vector{T}) where T
    s = zero(MA.promote_operation(+, T, T))
    for el in x
        MA.mutable_operate_to!(s, +, s, el)
    end
    return s
end
```
which only allocate one `ArbFloat`, `s`.
We have a similar function implemented for subtypes of `AbstractMutable`:
https://github.com/JuliaOpt/MutableArithmetics.jl/blob/1bd06e46049cdee1be32a1fb119352428f1b1f64/src/dispatch.jl#L9-L11
`ArbFloat` cannot be an subtype of `AbstractMutable` so we cannot change the behavior of `Base` functions. However, algorithms built on top of the MA API would see speedup if `ArbFloat` implements the MA API.
